### ISSUE TITLE
Causes webui problems

### ISSUE THREAD

**Issue by daneger** [omaralvarez/deluge-autoremoveplus#25] opened 2016-08-26 03:32 UTC
Not sure if it is just me, but as long as autoremoveplus is enabled I have problems using the webui from another computer. I can sometimes load the webpage but no info on current torrents or options. Sonarr has issues communicating with deluge as well. If I disable autoremoveplus everything works again.  Maybe I am doing something wrong? 

Deluge 1.3.13 py2.7 on windows server 2012R2
Autoremoveplus 0.6

**Comment by dgw** [comment] 2016-08-26 03:41
Sounds like a duplicate of #24, which should probably be reopened. Guess it's not just me. :/

**Comment by daneger** [comment] 2016-08-26 03:46
Darn, when I was looking at the issues I didn't notice the closed label so only seen the current 5, but yes, seems to be pretty much the same as yours.

**Comment by omaralvarez** [comment] 2016-08-26 08:29
Yes, this is the same issue. My bad, I thought it would be fixed quickly. I think I know what is happening now, please use the other issue anyway.

**Closed as completed by omaralvarez** 2016-08-26 08:29 UTC
Labels: duplicate
